# NUMPY

In [1]:
import numpy as np

In [2]:
arr = np.linspace(5, 10, 7)
arr

array([ 5.        ,  5.83333333,  6.66666667,  7.5       ,  8.33333333,
        9.16666667, 10.        ])

In [3]:
arr.size

7

In [6]:
arr = np.arange(64).reshape((8,8))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [8]:
arr.ravel() # return a one-dimensional view - don't change matrix or tensor, but change in new assign array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [9]:
arr1 = arr.ravel()
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [10]:
arr1[0] = 999
arr1

array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63])

In [11]:
arr

array([[999,   1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31],
       [ 32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60,  61,  62,  63]])

In [12]:
array = np.arange(25).reshape(5,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
flatten_arr = array.flatten() # inline change
flatten_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
flatten_arr[0] = 333
flatten_arr

array([333,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [15]:
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### np.resize() Danger!!!! 

* The .resize() same as .reshape() method, but in-memory changes

In [16]:
newarray = np.arange(0, 9).reshape(3,3)
newarray

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
newarray.resize(1,9)

In [20]:
newarray

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [21]:
# accessing an element of a 2d array
d2array = np.arange(25).reshape(5,5)
d2array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
d2array[0, 3], d2array[1, 2], d2array[2, -1], d2array[-1, 1]

(3, 7, 14, 21)

In [23]:
d2array[0:-1, 1:2]

array([[ 1],
       [ 6],
       [11],
       [16]])

In [25]:
d2array[0:2, -2:]

array([[3, 4],
       [8, 9]])

In [26]:
d2array[1:, 0:3]

array([[ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17],
       [20, 21, 22]])

In [27]:
d2array[2, 1:-1]

array([11, 12, 13])

In [32]:
d2array[-2:, -3:]

array([[17, 18, 19],
       [22, 23, 24]])

# Question:

What is the difference between indexing and slicing ??

**indexing:** get particular element, with its own datatype (int, float, etc). 

In [ ]:
d2array

In [42]:
a = d2array[4][2]   # returns and element of the array 22 that is int type 
a

22

In [43]:
type(a)

numpy.int64

**slicing:** get particular element or group with pack dataype (ndarray, list, etc).

In [44]:
a = d2array[1:4,2:3]   # notice the brackets around 22 shows its not an element but a 2d array with one element 22.
a

array([[ 7],
       [12],
       [17]])

In [45]:
type(a)

numpy.ndarray

### Combining array

Arrays can be combined in various ways. This process in NumPy is referred to as stacking. Stacking can take various forms, including horizontal, vertical, and depth-wise stacking. To demonstrate this

#### Horizontal (Col) stacking (side  by side or parallel)

Combines two arrays in a manner where the columns of the
second array are placed to the right of those in the first array. The function actually
stacks the two items provided in a two-element tuple. The result is a new array with
data copied from the two that are specified:

In [55]:
arr1 = np.arange(16).reshape(8,2)
arr1

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [56]:
arr2 = np.arange(16,56).reshape(8,5)
arr2

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55]])

In [57]:
np.hstack((arr1, arr2))

array([[ 0,  1, 16, 17, 18, 19, 20],
       [ 2,  3, 21, 22, 23, 24, 25],
       [ 4,  5, 26, 27, 28, 29, 30],
       [ 6,  7, 31, 32, 33, 34, 35],
       [ 8,  9, 36, 37, 38, 39, 40],
       [10, 11, 41, 42, 43, 44, 45],
       [12, 13, 46, 47, 48, 49, 50],
       [14, 15, 51, 52, 53, 54, 55]])

#### Vertical (Row) Stacking - up down

Vertical stacking returns a new array with the contents of the second array as
appended rows of the first array.

In [58]:
arr3 = np.arange(20).reshape(2,10)
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [59]:
arr4 = np.arange(20,60).reshape(4,10)
arr4

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [60]:
np.vstack((arr3, arr4))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

#### Depth stacking

Takes a list of arrays and arranges them in order along an additional
axis referred to as the depth:

In [61]:
arr5 = np.arange(9).reshape(3,3)
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
arr6 = np.arange(9,18).reshape(3,3)
arr6

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [63]:
np.dstack((arr5,arr6))

array([[[ 0,  9],
        [ 1, 10],
        [ 2, 11]],

       [[ 3, 12],
        [ 4, 13],
        [ 5, 14]],

       [[ 6, 15],
        [ 7, 16],
        [ 8, 17]]])

In [65]:
my_array = np.arange(36).reshape(6,6)
my_array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

#### Mean

In [67]:
my_array.mean()

17.5

#### Variance

In [68]:
my_array.var()

107.91666666666667

#### Standard deviation

In [66]:
my_array.std()

10.388294694831615

#### Sum and Product

In [69]:
my_array.sum()

630

In [70]:
my_array.prod()

0

#### CumSum and CumProduct

In [71]:
my_array.cumsum()

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325,
       351, 378, 406, 435, 465, 496, 528, 561, 595, 630])

In [72]:
my_array.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [73]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**.any:** `return True, if find any one True in an array otherwise False.`

In [76]:
a.any()

True

In [78]:
(a < 5).any()

True


**.all:** `return True, if find all True in an array otherwise False.`

In [75]:
a.all()

False

In [79]:
(a < 5).all()

False