# Numpy - [4.1, 4.2, 4.5, A3]

# 4.1 The NumPy ndarray: A Multidimensional Array Object

In [1]:
# !pip install numpy 

In [2]:
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [3]:
data = np.random.randn(2, 3)

In [4]:
data

array([[-1.13960763, -0.20499545,  0.43022034],
       [-0.53610431, -1.02969344, -0.48779063]])

In [5]:
data * 10

array([[-11.39607635,  -2.04995454,   4.30220344],
       [ -5.36104306, -10.29693436,  -4.87790627]])

In [6]:
data

array([[-1.13960763, -0.20499545,  0.43022034],
       [-0.53610431, -1.02969344, -0.48779063]])

In [7]:
data + data 

array([[-2.27921527, -0.40999091,  0.86044069],
       [-1.07220861, -2.05938687, -0.97558125]])

In [8]:
data.shape  # kitne BY kitne ka matrics hai - [row x col]

(2, 3)

In [9]:
data.dtype

dtype('float64')

## Creating ndarrays

In [10]:
data1 = [1, 5, 7, 3]

In [11]:
arr1 = np.array(data1)

In [12]:
arr1

array([1, 5, 7, 3])

In [13]:
data2 = [[1, 5, 7, 3], [8, 5, 2, 2]]

In [14]:
arr2 = np.array(data2)

In [15]:
arr2

array([[1, 5, 7, 3],
       [8, 5, 2, 2]])

In [16]:
arr2.shape

(2, 4)

In [17]:
arr2.ndim

2

In [18]:
arr3 = np.ones((3,6))
arr3

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [19]:
arr3 = np.ones_like(arr2)
arr3

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [20]:
arr3 = np.zeros(10)
arr3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
arr3 = np.zeros((3,6))
arr3

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
arr3 = np.zeros_like(arr2)
arr3

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [23]:
arr3 = np.empty((2, 3, 2))
arr3

array([[[4.65966975e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [24]:
arr3.shape

(2, 3, 2)

In [25]:
arr3.ndim

3

In [26]:
arr3 = np.empty_like(arr2)
arr3

array([[    94312768018752,                  0,                  0,
                         0],
       [                 0,                  0, 586321318746458127,
           281874581162549]])

In [27]:
arr4 = np.arange(16)
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
arr4.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
arr3 = np.full((2, 3), 19)
arr3

array([[19, 19, 19],
       [19, 19, 19]])

In [30]:
arr3 = np.full_like(arr2, 17)
arr3

array([[17, 17, 17, 17],
       [17, 17, 17, 17]])

In [31]:
arr3 = np.eye(4)
arr3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
arr3 = np.identity(4)
arr3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Data Types for ndarrays

In [33]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr.dtype

dtype('int64')

In [35]:
float_type = arr.astype(np.float64)
float_type

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [36]:
float_type.dtype

dtype('float64')

In [37]:
arr = np.arange(0, 20, 3.5)
arr

array([ 0. ,  3.5,  7. , 10.5, 14. , 17.5])

In [38]:
arr.dtype

dtype('float64')

In [39]:
int_type = arr.astype(np.int64)
int_type

array([ 0,  3,  7, 10, 14, 17])

In [40]:
int_type.dtype

dtype('int64')

## Arithmetic with NumPy Arrays

In [41]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [42]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [43]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [44]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
arr + arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [46]:
arr / arr 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [47]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [48]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [49]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [50]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## Basic Indexing and Slicing

In [51]:
arr = np.arange(10)

In [52]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr[5]

5

In [54]:
arr[2:8]

array([2, 3, 4, 5, 6, 7])

In [55]:
arr[2:8] = 12
arr

array([ 0,  1, 12, 12, 12, 12, 12, 12,  8,  9])

In [56]:
arr_slice = arr[2:8]
arr_slice

array([12, 12, 12, 12, 12, 12])

In [57]:
arr_slice[1] = 12345

In [58]:
arr_slice

array([   12, 12345,    12,    12,    12,    12])

In [59]:
arr

array([    0,     1,    12, 12345,    12,    12,    12,    12,     8,
           9])

In [60]:
arr_slice[:] = 12345

In [61]:
arr

array([    0,     1, 12345, 12345, 12345, 12345, 12345, 12345,     8,
           9])

#### Use Copy method for expicitly copy

In [62]:
sliced = arr[5:8].copy()
sliced

array([12345, 12345, 12345])

In [63]:
sliced[1] = 45678

In [64]:
sliced

array([12345, 45678, 12345])

In [65]:
arr

array([    0,     1, 12345, 12345, 12345, 12345, 12345, 12345,     8,
           9])

In [66]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr2d[2]

array([7, 8, 9])

In [68]:
arr2d[2][1]

8

In [69]:
arr2d[2, 1]

8

#### Multi-dimensional array

In [70]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [71]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
old_values = arr3d[0].copy()

In [74]:
old_values.shape

(2, 3)

In [75]:
arr3d[0] = 42

In [76]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
arr3d[0] = old_values

In [78]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [79]:
arr3d[1, 0]

array([7, 8, 9])

In [80]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
arr2d[0]

array([1, 2, 3])

In [82]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [84]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [85]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## Boolean Indexing

In [86]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [87]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [88]:
data = np.random.randn(7, 4)
data

array([[ 2.80509946e+00, -1.11853883e+00,  1.11697257e+00,
         8.81561626e-01],
       [-1.90149493e-03, -1.14345788e+00,  1.33283199e-01,
        -1.55457746e-01],
       [-3.47956389e-01,  1.46323426e+00, -7.19638179e-01,
        -6.76902710e-01],
       [ 1.82342227e-01, -9.10762664e-01,  9.02022695e-03,
         8.55283649e-02],
       [-2.36518181e-01,  6.58438164e-01,  1.28864062e+00,
         8.41395711e-01],
       [ 4.38164980e-01,  4.51883574e-01, -2.71391996e-01,
        -2.23719612e+00],
       [ 5.76737368e-01, -9.60600199e-01, -3.34457298e-01,
         1.03211351e+00]])

In [89]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [90]:
data[names == 'Bob']

array([[ 2.80509946, -1.11853883,  1.11697257,  0.88156163],
       [ 0.18234223, -0.91076266,  0.00902023,  0.08552836]])

In [91]:
data[names == 'Bob', 2:]

array([[1.11697257, 0.88156163],
       [0.00902023, 0.08552836]])

In [92]:
data[names == 'Bob', 3]

array([0.88156163, 0.08552836])

In [93]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [94]:
data[mask]

array([[ 2.80509946, -1.11853883,  1.11697257,  0.88156163],
       [-0.34795639,  1.46323426, -0.71963818, -0.67690271],
       [ 0.18234223, -0.91076266,  0.00902023,  0.08552836],
       [-0.23651818,  0.65843816,  1.28864062,  0.84139571]])

In [95]:
mask2 = (names == 'Bob') & (names == 'Will')
mask2

array([False, False, False, False, False, False, False])

In [96]:
data[mask2]

array([], shape=(0, 4), dtype=float64)

In [97]:
data[data < 0] = 0

In [98]:
data

array([[2.80509946, 0.        , 1.11697257, 0.88156163],
       [0.        , 0.        , 0.1332832 , 0.        ],
       [0.        , 1.46323426, 0.        , 0.        ],
       [0.18234223, 0.        , 0.00902023, 0.08552836],
       [0.        , 0.65843816, 1.28864062, 0.84139571],
       [0.43816498, 0.45188357, 0.        , 0.        ],
       [0.57673737, 0.        , 0.        , 1.03211351]])

In [99]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.1332832 , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.43816498, 0.45188357, 0.        , 0.        ],
       [0.57673737, 0.        , 0.        , 1.03211351]])

## Fancy Indexing

In [100]:
arr = np.empty((8, 4))

In [101]:
for i in range(8):
    arr[i] = i

In [102]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [103]:
arr[[4, 6, 5, 2]]

array([[4., 4., 4., 4.],
       [6., 6., 6., 6.],
       [5., 5., 5., 5.],
       [2., 2., 2., 2.]])

In [104]:
arr[[-3, -1, -6]]

array([[5., 5., 5., 5.],
       [7., 7., 7., 7.],
       [2., 2., 2., 2.]])

In [105]:
arr = np.arange(32).reshape((8, 4))

In [106]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [107]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

## Transposing Arrays and Swapping Axes

In [108]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [109]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [110]:
arr = np.random.randn(6, 3)
arr

array([[ 0.14115061, -1.45161882, -2.27101128],
       [ 2.04840773,  1.11046141, -0.01820523],
       [ 0.49981148,  0.2166454 ,  0.15107202],
       [-0.56245564,  1.01969359,  1.79987607],
       [ 0.59188078,  0.47379263,  0.82588329],
       [-1.07538715, -1.44419199, -0.64744989]])

In [111]:
# arr1: row x col => 3 x 6 
# arr2: row x col => 6 x 3

# arr1_row === arr2_col (for dot product)

np.dot(arr.T, arr)

array([[ 6.28884598,  3.43802456, -0.10960554],
       [ 3.43802456,  6.73720195,  6.47081702],
       [-0.10960554,  6.47081702,  9.52147486]])

#### Transpose for higher dimension 

In [112]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [113]:
arr.transpose((1, 0, 2)) # give axis

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [114]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

# 4.2 Universal Functions: Fast Element-Wise Array Functions

In [115]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [117]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [118]:
x = np.random.randn(8)
x

array([ 1.49244075, -0.0719998 , -1.32922536, -0.87078695, -0.89618305,
        0.1866954 , -0.13073399, -1.15046271])

In [119]:
y = np.random.randn(8)
y

array([ 0.34185611,  0.88181365, -0.86509847,  1.11108474,  0.08008551,
       -0.96697862,  0.25881477,  0.56282289])

In [120]:
np.maximum(x, y)

array([ 1.49244075,  0.88181365, -0.86509847,  1.11108474,  0.08008551,
        0.1866954 ,  0.25881477,  0.56282289])

In [121]:
arr = np.random.randn(7) * 5
arr

array([ 8.7029704 ,  5.74832071,  3.00335334, -3.10945084, -7.70376462,
        9.16570395,  1.7772892 ])

In [122]:
remainder, whole_part = np.modf(arr)

In [123]:
remainder

array([ 0.7029704 ,  0.74832071,  0.00335334, -0.10945084, -0.70376462,
        0.16570395,  0.7772892 ])

In [124]:
whole_part

array([ 8.,  5.,  3., -3., -7.,  9.,  1.])

In [125]:
np.sqrt(arr)

array([2.95007973, 2.39756558, 1.73301856,        nan,        nan,
       3.02749136, 1.3331501 ])

In [126]:
arr

array([ 8.7029704 ,  5.74832071,  3.00335334, -3.10945084, -7.70376462,
        9.16570395,  1.7772892 ])

In [127]:
np.sqrt(arr, arr)

array([2.95007973, 2.39756558, 1.73301856,        nan,        nan,
       3.02749136, 1.3331501 ])

In [128]:
arr

array([2.95007973, 2.39756558, 1.73301856,        nan,        nan,
       3.02749136, 1.3331501 ])

# 4.5 Linear Algebra

In [129]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [130]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [131]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [132]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [133]:
x @ np.ones(3) # "@" infix operator that performs dot matrix multiplication

array([ 6., 15.])

In [134]:
from numpy.linalg import inv, qr

In [135]:
X = np.random.randn(5, 5)
X

array([[-0.41691031,  0.77225553, -0.64994767, -1.07050671, -1.41847361],
       [ 0.25660885, -0.81912184,  2.05890584, -1.68404642, -0.44877352],
       [ 0.66939017,  0.36934437, -2.42893584,  2.48452339,  0.52917861],
       [-1.10654168,  2.24107464,  1.11707311, -0.71436566, -2.33992865],
       [ 1.71247284,  0.59684597, -0.68710903, -0.03483542, -0.34920389]])

In [136]:
mat = X.T.dot(X)
mat

array([[ 4.84474324, -1.74267969, -3.23934593,  2.40810028,  2.82167038],
       [-1.74267969,  6.7823951 , -0.99218824, -0.15135894, -5.98475044],
       [-3.23934593, -0.99218824, 12.28122569, -9.58033052, -3.66131993],
       [ 2.40810028, -0.15135894, -9.58033052, 10.66638525,  5.27272694],
       [ 2.82167038, -5.98475044, -3.66131993,  5.27272694,  8.09070449]])

In [137]:
inv(mat)

array([[ 0.30822755, -0.04600554,  0.12455156,  0.12352152, -0.16566176],
       [-0.04600554,  2.43806134, -0.03950018, -1.29984615,  2.64873252],
       [ 0.12455156, -0.03950018,  0.33904089,  0.34803319, -0.14604278],
       [ 0.12352152, -1.29984615,  0.34803319,  1.14887634, -1.59581186],
       [-0.16566176,  2.64873252, -0.14604278, -1.59581186,  3.11456399]])

In [138]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -8.88178420e-16,  5.55111512e-17,
         0.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00,  1.11022302e-16,
         0.00000000e+00, -7.10542736e-15],
       [-1.11022302e-16,  1.77635684e-15,  1.00000000e+00,
        -1.77635684e-15,  0.00000000e+00],
       [-1.11022302e-16,  0.00000000e+00, -4.44089210e-16,
         1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -2.22044605e-16,
         1.77635684e-15,  1.00000000e+00]])

In [139]:
q, r = qr(mat)

In [140]:
r

array([[ -7.12478788,   4.81415279,  12.23184571, -11.72358062,
        -10.0335071 ],
       [  0.        ,  -7.91747015,   6.16274851,  -3.47978177,
          5.40470324],
       [  0.        ,   0.        ,  -8.93849997,   9.16879588,
          4.35022705],
       [  0.        ,   0.        ,   0.        ,  -2.35795919,
         -1.25981522],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.22755688]])

# A.3 Broadcasting

In [141]:
arr = np.arange(5)

In [142]:
arr

array([0, 1, 2, 3, 4])

In [143]:
arr * 4

array([ 0,  4,  8, 12, 16])

In [144]:
 arr = np.random.randn(4, 3)
arr

array([[-0.85676851,  0.4025103 , -0.53658154],
       [ 0.25412569,  0.02377338, -0.66628525],
       [ 0.40565061, -0.83713936,  0.097429  ],
       [ 1.73738234, -0.65383792,  0.54643164]])

In [145]:
arr.mean(0) # axis = 0 [row-wise]

array([ 0.38509753, -0.2661734 , -0.13975153])

In [146]:
demeaned = arr - arr.mean(0)

In [147]:
demeaned

array([[-1.24186604,  0.6686837 , -0.39683   ],
       [-0.13097185,  0.28994678, -0.52653371],
       [ 0.02055308, -0.57096596,  0.23718054],
       [ 1.35228481, -0.38766452,  0.68618318]])

In [148]:
demeaned.mean(0)

array([-5.55111512e-17,  1.38777878e-17, -5.55111512e-17])

In [149]:
arr

array([[-0.85676851,  0.4025103 , -0.53658154],
       [ 0.25412569,  0.02377338, -0.66628525],
       [ 0.40565061, -0.83713936,  0.097429  ],
       [ 1.73738234, -0.65383792,  0.54643164]])

In [150]:
row_means = arr.mean(1)
row_means

array([-0.33027991, -0.12946206, -0.11135325,  0.54332535])

In [151]:
row_means.shape

(4,)

In [152]:
row_means.reshape((4, 1))

array([[-0.33027991],
       [-0.12946206],
       [-0.11135325],
       [ 0.54332535]])

In [153]:
arr - arr.mean(1).reshape(4,1)

array([[-0.52648859,  0.73279021, -0.20630162],
       [ 0.38358775,  0.15323544, -0.53682319],
       [ 0.51700386, -0.72578611,  0.20878225],
       [ 1.19405699, -1.19716328,  0.00310629]])